### ISSUE TITLE
Your browser does not support WebGL

### ISSUE THREAD

**Issue by riccicedric** [zzxzzk115/NW-Unity#1]
Unity 2019.3.12f1
Gamshell Linux 5.3.6-clockworkpi-cpi3armv7|GNU/Linus
OS Image V0.5
nwjs-sdk-v0.27.6-linux-arm

I followed your instruction and when I launch my game on the Gameshell I receive the following popup message :
**Your browser does not support WebGL** [OK]
 _(probably coming from the UnityLoader.js)_

**Comment by zzxzzk115** [comment]
Hi, riccicedric. You might use Lima driver. Lima is still an experimental GPU driver. You can change your driver to FBTurbo(Software Rendering) and retry.

**Comment by zzxzzk115** [comment]
> Unity 2019.3.12f1
> Gamshell Linux 5.3.6-clockworkpi-cpi3armv7|GNU/Linus
> OS Image V0.5
> nwjs-sdk-v0.27.6-linux-arm
> 
> I followed your instruction and when I launch my game on the Gameshell I receive the following popup message :
> **Your browser does not support WebGL** [OK]
> _(probably coming from the UnityLoader.js)_

**Comment by riccicedric** [comment]
Now I can launch my game build, but after the unity logo nothing is shown...
The screen stays black, by any chance do you have a Unity project template to check what is different with mine?
Also here is my WebGL build with your file added, in case you want to test on a Gameshell, and see what is happening: [](https://1drv.ms/u/s!Av7OsA17G4T5ibsb0EPMIbuHRLD7jw?e=hpbwxw)

**Comment by zzxzzk115** [comment]
Maybe you should export the Game with another template(Not Minimal), maybe I was wrong.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Cédric Ricci"<notifications@github.com&gt;; 
发送时间: 2020年4月30日(星期四) 晚上8:22
收件人: "zzxzzk115/GameShell-Unity3D-WebGL"<GameShell-Unity3D-WebGL@noreply.github.com&gt;; 
抄送: "zkx"<954294627@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [zzxzzk115/GameShell-Unity3D-WebGL] Your browser does not support WebGL (#1)





 
Now I can launch my game build, but after the unity logo nothing is shown...
 The screen stays black, by any chance do you have a Unity project template to check what is different with mine?
 Also here is my WebGL build with your file added, in case you want to test on a Gameshell, and see what is happening:
